### ISSUE TITLE
Unable to see bottom row of Completed subtab on Research tab

### ISSUE THREAD

**Issue by trawls** [pmotschmann/Evolve#791] opened 2022-08-18 01:17 UTC
On the subtab containing the completed research, I am unable to see the bottom tab. I am playing on a laptop, so the smaller display size may be the factor here.

I have included a screen shot below.

Display resolution:
![DisplayDetails](https://user-images.githubusercontent.com/26367739/185270865-0657f257-efff-42b8-89c1-915efc4b4d2f.PNG)

View:
![CompletedResearchDisplay issue](https://user-images.githubusercontent.com/26367739/185270882-e88bf3bc-572a-43c3-894b-7bb4b4b08c71.PNG)

**Comment by trawls** [comment] 2022-08-18 01:18
Oops, I meant to highlight where it cuts off my completed Space Mining research items. Earlier in my progression it was doing this t the Temples & Religion section.

**Comment by SkyCharger001** [comment] 2022-09-13 12:48
The problem is due to how the credit line and main view are laid out. (instead of putting the line below the main view, it's placed over its bottom.)

**Comment by pmotschmann** [comment] 2023-03-21 02:45
was fixed in 1.3.0

**Closed by pmotschmann** 2023-03-21 02:45 UTC
