### ISSUE TITLE
Money cap is less than needed to build a next level bank

### ISSUE THREAD

**Issue by Areso** [pmotschmann/Evolve#50] opened 2019-05-09 17:05 UTC
Current money cap is 11k
Current bank level is 10.
Next bank level is 11, 14 416 is needed to build one.

**Comment by Areso** [comment] 2019-05-09 17:11
N4IgzgphAmIFwGYCcKA0IBOEwHsCuGAxhPKAEoByAgqSAHYCGAtiXCJTetAJZgAOAGwYBPeADMGAyOmb46AF3gAmABwA6AKzpCGBvOzwADF25ixRrhAHyGFkEwYAPeAEYXCLZj2sX2nAoZuOggMMCMAX3QAEWpaRhZ4EBjOEB5+IVE4CSkIGSY5RTgAFk8dbzC4Y1TTc0rLa1s6+yd4IoQq3X1XPwCgkIrDSJAAWX8ITNB41hAAEhATdJF4eQw8XJBZPAV4JCKVAHY1IsMT05OXADYlbU6DJp4zV3UEC/qbOwdnODdT9Fvu8A2QgAawYACMBKxstIQIR/DY+qEIugAMIQAIEOLMaZojEYebVRaZFZrPIFVq+WG3AYmR73KzvJqfCl/bx2MBA0EQqGSGFw3rBJGVIYAaToOAA7pDoABzViTbGJMWS6VyglpQRLOAk9abbbfK6GNRIJQaM4nfYISllfQ06p0lxqSnQBmNKrMxAeDps77oDkMEHgyHiXnrfkIwUDIYo6lYhJsGPldW8TXE1a6/JbQpVG13KoPWr510fFpwM2srpNf2B7khnI9CP9ZEgFHwwKRuM4tuIsILVN1mF67M3JP3Gp2F0NEtfb2VqrVrnBrKhhvtpvC9AAMRwOFgcAV8ZA293yaJy3T6AAbpI1vANGp9vsUM+X8+VJ4h3eUEo1Ep9oYEEAwDVHfEdbQncc4EOQwVDeN10A9C5fi8StKQXINWB1VcezsFYGBdZsABk8CYMEQk7RJiNI8i+wyc9SRAa8BFvOALjUQ1zU4j9M31F4TjAvNaVqQ4lCQODp3gPjZx8P1OQw+iw27DsmjwgiNxAABleQxgotgtJ02itSwxib1YNin04zjKU/OAlBcOy1BeIoilfC4NDEqlR3zSCfxUa5UmLJlS2OfiUJkwEA0XTCL1hJT1yqVTWEGLcCAqA9pk3VLT37bUYqYljDj2SyzhcDRuPJb4QoEu0C2UNRDH2cSgq+FwqrCgF0NrXKGPDNchQS3Q1OSlscD4PhyP3ehFQTUbxvxQy0wY/LWFUB93NfV8DjJLNXAa0pYzHOkjXcpr3VLFw9orcLOqXYzepwlTBqSoYAEkMH8XSQDej6FoUq9TMk+8NCUYrTmsnjCla0LcxqyDHQA06EPOtr/l9CKa1umL7uUgb8Oe1EIBYfV0sSNEicUX7uvWZbXCKB8LtBwwXA8myLpElAzXNJQXkazzwMOwsH38ydGTOlqoaujq5K6u64v69BEubVtJE+5WBGyujl3rEzmJWqobJzA7vKOxHmi+f9pKlyL5Kp7CcYVp7mwAeW4dXJqmRIXfVynoWpgGoPKnamhhiCTYCqdmrsVG0Olpdfbt+KHbx5sAFVdDobgSM+tOGAzrOfZXHWWLK/WIbsEOBYnQKxd2yW0ZunltexxOQEV9StKgN2Sb0/QrA1rV46LnxQoN6rQ8LU2PXLdr69j6Kerlu02+GgAVbgbDzphPrXjfM63gvtZp75p9HvnBPtCfw9FpGvmn6PZOtmWscX3DHfUqgBAEHAJimw8P6/0QB8YRHz/IHfUhsvJCSrhHGuZZLaz0fpjBeAoW7LyGAABRwAIYQLB8Tu2miATB2DcH90yIPEBpptrgLHpXekMCb53ngTHRB89FIoPlq3N+w10HYIlDuPc3dCG8P4aQv6Gwy62QApoTmxU/w0ONpfEW8EzbwAALSUlRvOOeA42GNn6kMAAQhgbgIJPpGJMcCURttxEVRUEafYIVQZFHkVAuh18VFwHUXXLRLCdEJ30egIx/gABe8pf7TCCXQUJVjB6nwrgo6B7iPReJnj4jGjc+Qv3UgAdXengGUAALeQAB9b6dBPq5PwIUkpZSrHGRskoNihgXIbRfCoV4Z9YZhyURJTxGifRpKin42K7CozoA0gUqAJThgQBsF3cJiQJlTOKTMuZMTC5xKNq4os9CPEpM0Q/dJwzm76KGBAS8WC8DyG4B9Sa0BGAAhYKRdOYS4RBwuEgIYOAMAylzlYSEaVYpBxcCoIYdA8CEEhHgQFbz9QXTOXgUEGBhA4GuYQYpxBP60FhZDFwQwmDrxwIQAp/hoDGMaKAHFyghiQEcHgSQxSsB8HetACF1zbmUoqni9AfACkMBlES4Q2kwC8GxVyoYYgggq2+KFJgeBrAmP+fKhgeDOXAqGGCV23hdACGKWAHBLAVg/ypd8fFzAHBSDFeqv06JrnomIFauF4Qhj6GJbQZl3ACXXMvKwBAMgZTGMIPK+QBBfXoBJdCoIMopbfP5eFINGAsB0EIJkfyBKM50GjYgGQjgVp+kINwe1Yb7Cu3Xiq1N6AwS52BFG5Q2hCa2oBBIDAW80Z8qYCQtGYg5Bkora3SZegsB1pAHwCxThwokvCiq/IeDrRy1cEMAt8gf4zskK8ggSbChIC0VgMAFR1H+VtSECMw7IAMFwOUpoEoIB6EmXg4ahA110GgCq2gL7MitV5sIG9s6PJnovQCa9t6Jr+X0EwPgjydyXsoSACUQQ9yUm+ZqwoLwNBDD4JKEIMBhkYevfeytNzDwBvPWAIQz6CQOAwMCWZtAACOy7EgMwo8vJOQ0ZCEG9RkiAQxmLUVnTyzDGBinaTWU0Ztra1VwouBq89JjikRpFZmx1hRTQ0smQIoFcKEBDHeiCYptH6WJuNVy/ytzhq8bIkJ4QKqNMmtBegLY3AfWhHXsZ95QxfmJt4ByzThQ0N+ldjgZTu0ZN0EsZNE18KEJ9GC8UdAZnF0NoUMUzUxNfMAgS+gbtWxe2xf2gwMQ1ylNlnQDw4QfCTxo3MaY7NIBInRKaJU/JRTSnvUvZSJZsyVmzOlcNZgvL14DpWK88V6ABDcDBLoZFsWlA0u0roOUxTrMYFs+KxdTmTG0DEFgJKWXp0TVAAAKxwGCRI4maILLYJufb81CQ5WMnwqj65LgMINOgT1fAAwqc0DxkilnDuRVoMd07bALMhAB6Y9AHs2BUX+4DymD3vnUaFB0j0L2QAfa+wu9ABmVXIuKY95HQOTuJFx0ZgnSOLvQ5AAARUM8igABNkynt2NSa0R09oUvM0f+Uxxx7HJbBTE5B4LqnBDhiIjqTFQn65nEeLl3zyGi6cAMvTQdkAwPEhwlV5LqHBC1YM4l0LoB6wZccI9FURXRhfyLt0IVsADhL1HZJ2wMo9vHcEmp4md3ucpcMTNxUTwU93vgax6a+t5MKec+F1rpLJSzee/13HhnPDc7yCZyzv3puWcVDTaWXnof+eVCOGchQx6+ox7YEejAejE+HgAKJl5rxXhH0uc+PPOiHz7RfuUjvemIbAuBVUa5d33nAA+93fLr9MdB/fB9T9b/79vkdWJd7D8dWb+bC0KF4IUZ3IuwAFttbv6fiyj8745Os7WAfemW8L0ryt1b1ea7YFWsLYvDwGKf6zlM7O2+c7tDRzv272zCdBdXHUBRsEcEZR9BACUCv0gA8zx28ydzuz/wYjSAwj3EHmZRwADUH1wi+02zi1g2XwunQD4Ry2wyaF0G4D3FgXIPsBCEIAqF9jNQ0zZwHg2RbWoJ1GdVZAdUmn4AgCPwqFhFtQYExHQAFWgDEPFGCAJFTwdzoNi2GjlRsHZUvSqDInPUhm0EkPZWhQBB0I5GKXH2KTBAIBdHa3DRCE1QuSHXDxADlGCDSjmz0EBX9Br1cDKktDsSQBUEuGQC4BEAqH/ECIVnfTtF3RoyaE1GUPoIfgwB9USNbi8JSIgmoISh4CyPQGBHFAlFcEfC2lbnyMlDsADAKULR9VIH4JAHOUbTgECLl2CEKK1mAX6BuUvRACNB/D2AJEgHkCKxlBhScxXnBAqD/RJQlHrwuQEBqPaPWDAGmJRFczEWWMlBemfWhSNWGQ2IlDIGwB/TdWsX2NWMvGIOMn2OGBVWo0KCuOmIAHF0RZkTFWDC59iNJu8uM/RpiqBiVqifiNgM4HB9BsDC5MDuRDjBjhl5BJlDwX0qMCQVVPtaAUSGBxiwQ7ReVhARUWCxEXDXj8TFibgUw8E2CeNdDhgwAs1QBW0QAqA6AGc9BOQGcwRhBmSGdjEmIGcl0OS+UwA2SoAmSmV/kYBUAGdDAGdcABAcjQgGc8MIAGca1P4YBmTn1JTpSsE5TBTFSFSe0YA1ACRCBEgJQVUM1o0hh0TajwggA

**Comment by pmotschmann** [comment] 2019-05-09 17:16
Duplicate of #32

**Comment by CapnCrinklepants** [comment] 2019-05-10 03:45
There are later researches that will make the next bank possible, and future plans to make this clearer. Not actually an issue :)

**Closed** 2019-05-11 03:29 UTC
