### ISSUE TITLE
Request: see recipe on queue mouseover

### ISSUE THREAD

**Issue by lxsli** [pmotschmann/Evolve#378] opened 2020-06-30 12:43 UTC
This would make it easier to see, for example, which material can be bought to accelerate completion. This would reduce the amount of flipping between screens that's necessary. You can also play with trades' impact on the ETA but this doesn't help if you forget the recipe.

**Comment by pmotschmann** [comment] 2020-07-14 02:40
Duplicate of #320

**Closed by pmotschmann** 2020-07-14 02:40 UTC
