### ISSUE TITLE
Are you open to CSS pull requests?

### ISSUE THREAD

**Issue by StoneCypher** [pmotschmann/Evolve#279] opened 2019-12-30 19:48 UTC
I'd like to fix #269, and a few other things like it

**Comment by pmotschmann** [comment] 2019-12-30 21:18
Duplicate of #269 please contain discussion to a single thread

**Closed by pmotschmann** 2019-12-30 21:18 UTC
Labels: duplicate

**Comment by StoneCypher** [comment] 2019-12-30 23:04
well, i also meant stuff like "could i donate a theme" and whatever

**Comment by StoneCypher** [comment] 2019-12-30 23:05
i guess i might have, y'know, said that

**Comment by pmotschmann** [comment] 2019-12-30 23:21
Absolutely you can. The current themes are all defined in src/evolve.less. I tried to keep the theming aspects of it separated from the rest of the styling code near the bottom. You can use an existing theme as a base this way or just start fresh.
